<a href="https://colab.research.google.com/github/VictorTrigo/Estadistica-Computacional/blob/master/leccion09.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
## TALLER 6: SISTEMMA DE ECUACIONES NO LINEALES

Sea $F:\mathbb{R}^2 \rightarrow \mathbb{R}^2$ dado por:
 
 $$F(x)=\left(\begin{array}{c}
 x_1^2 + x_2^2 - 2\\
 e^{x_1-1} + x_2^3 -2
 \end{array}\right)$$
 
Entonces el Jacobiano es

 $$J_F(x)=\left(
 \begin{array}{cc}
 2x_1 & 2x_2\\
 e^{x_1-1} & 3x_2^2 
 \end{array}\right)$$
 
 con punto de partida $x_0 = (1,5; 2)^T$ y criterio de parada $||F(x_k)||_2 \leq 10^{-10}$

In [ ]:
import numpy as np

In [ ]:
def F(x):
    x = np.array(x)
    F1 = x[0]**2 + x[1]**2-2
    F2 = np.exp(x[0]-1) + x[1]**3 - 2
    return np.matrix(np.append(F1,F2)).T


In [ ]:
F([1.5,2])

matrix([[4.25      ],
        [7.64872127]])

In [ ]:
def F(x):
    x = np.array(x)
    F = np.zeros((2,1))
    F[0] = x[0]**2 + x[1]**2-2
    F[1] = np.exp(x[0]-1) + x[1]**3 - 2
    return np.matrix(F)

In [ ]:
F([1.5,2])

matrix([[4.25      ],
        [7.64872127]])

In [ ]:
def JF(x):
    x = np.array(x)
    JF11 = 2*x[0] 
    JF12 = 2*x[1] 
    JF21 = np.exp(x[0]-1)
    JF22 = 3*x[1]**2 
    return np.matrix([np.append(JF11,JF12),np.append(JF21,JF22)])

In [ ]:
JF([1.5,2])

matrix([[ 3.        ,  4.        ],
        [ 1.64872127, 12.        ]])

In [ ]:
def JF(x):
    x = np.array(x)
    J = np.zeros((2,2))
    J[0][0] = 2*x[0] 
    J[0][1] = 2*x[1] 
    J[1][0] = np.exp(x[0]-1)
    J[1][1] = 3*x[1]**2 
    return np.matrix(J)

In [ ]:
JF([1.5,2])

matrix([[ 3.        ,  4.        ],
        [ 1.64872127, 12.        ]])

In [ ]:
x0 = np.matrix([1.5,2.1]).T
xn = x0
Fx = F(xn)
JFx = JF(xn)
iteracion = 0
print("Iteracion %d, ||x|| = %.12f, ||F|| = %.12f" %(iteracion, np.linalg.norm(xn), np.linalg.norm(Fx)))
while np.linalg.norm(Fx)>= 10**-10: 
    sn = - JFx.I*Fx
    xn = xn + sn
    Fx = F(xn)
    JFx = JF(xn)
    iteracion = iteracion + 1
    print("Iteracion %d, ||x|| = %.12f, ||F|| = %.12f , ||s|| = %.12f" %(iteracion, np.linalg.norm(xn), np.linalg.norm(Fx), np.linalg.norm(sn)))
print("Solucion. ||x|| = %.12f, ||F|| = %.12f" %(np.linalg.norm(xn), np.linalg.norm(Fx)))
print("Solucion. x = (%.12f, %.12f)" %(xn[0],xn[1]))

Iteracion 0, ||x|| = 2.580697580113, ||F|| = 10.054786577624
Iteracion 1, ||x|| = 1.698470015423, ||F|| = 2.454881588066 , ||s|| = 0.940638290360
Iteracion 2, ||x|| = 1.458715812771, ||F|| = 0.514911751967 , ||s|| = 0.357563731979
Iteracion 3, ||x|| = 1.427343788397, ||F|| = 0.088170022163 , ||s|| = 0.193158717834
Iteracion 4, ||x|| = 1.414541377306, ||F|| = 0.002703381966 , ||s|| = 0.030451734127
Iteracion 5, ||x|| = 1.414214057283, ||F|| = 0.000003659339 , ||s|| = 0.001183138088
Iteracion 6, ||x|| = 1.414213562374, ||F|| = 0.000000000006 , ||s|| = 0.000001485766
Solucion. ||x|| = 1.414213562374, ||F|| = 0.000000000006
Solucion. x = (0.999999999999, 1.000000000002)
