<a href="https://colab.research.google.com/github/VictorTrigo/Estadistica-Computacional/blob/master/leccion10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Propiedades de Matrices

In [ ]:
import numpy as np
import scipy.linalg as linalg

Definicion

In [ ]:
Lista = [[4, 7, -2], [1, -6, 8], [-3, 10, 6]]
Arreglo = np.array(Lista)
Matriz = np.matrix(Lista)

In [ ]:
Lista

[[4, 7, -2], [1, -6, 8], [-3, 10, 6]]

In [ ]:
Arreglo

array([[ 4,  7, -2],
       [ 1, -6,  8],
       [-3, 10,  6]])

In [ ]:
Matriz 

matrix([[ 4,  7, -2],
        [ 1, -6,  8],
        [-3, 10,  6]])

In [ ]:
3*Lista

[[4, 7, -2],
 [1, -6, 8],
 [-3, 10, 6],
 [4, 7, -2],
 [1, -6, 8],
 [-3, 10, 6],
 [4, 7, -2],
 [1, -6, 8],
 [-3, 10, 6]]

In [ ]:
3*Arreglo

array([[ 12,  21,  -6],
       [  3, -18,  24],
       [ -9,  30,  18]])

In [ ]:
3*Matriz

matrix([[ 12,  21,  -6],
        [  3, -18,  24],
        [ -9,  30,  18]])

In [ ]:
A2 = np.array([[1,1,1],[1,1,1],[1,1,1]])
M2 = np.matrix(A2)
M2

matrix([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [ ]:
Arreglo*A2 # Producto elemento a elemento. Producto de Hadamard

# a_{11} = 4*1 = 4
# a_{21} = 1*1 = 1
# a_{31} = -3*1 = -3
# ....

array([[ 4,  7, -2],
       [ 1, -6,  8],
       [-3, 10,  6]])

In [ ]:
Matriz*M2 # Producto Matricial

# a_{11} = 4*1+ 7*1 -2*1 = 9
# a_{21} = 1*1 + -6*1 + 8*1 = 3
# a_{31} = -3*1 + 10*1 + 6*1 = 13
# ....

matrix([[ 9,  9,  9],
        [ 3,  3,  3],
        [13, 13, 13]])

Operaciones

In [ ]:
Matriz

matrix([[ 4,  7, -2],
        [ 1, -6,  8],
        [-3, 10,  6]])

In [ ]:
Matriz.T # Matriz Transpuesta

matrix([[ 4,  1, -3],
        [ 7, -6, 10],
        [-2,  8,  6]])

In [ ]:
np.diag(Matriz) # Diagonal de la matriz

array([ 4, -6,  6])

In [ ]:
np.diag(np.diag(Matriz)) # Matriz diagonal

array([[ 4,  0,  0],
       [ 0, -6,  0],
       [ 0,  0,  6]])

In [ ]:
np.tril(Matriz) # Matriz Triangular inferior

array([[ 4,  0,  0],
       [ 1, -6,  0],
       [-3, 10,  6]])

In [ ]:
np.triu(Matriz) # Matriz Triangular superior

array([[ 4,  7, -2],
       [ 0, -6,  8],
       [ 0,  0,  6]])

In [ ]:
#Propiedad M = triangular_sumerior + triangular_inferior - diagonal
np.tril(Matriz)+np.triu(Matriz)-np.diag(np.diag(Matriz)) 

array([[ 4,  7, -2],
       [ 1, -6,  8],
       [-3, 10,  6]])

In [ ]:
np.trace(Matriz)

4

In [ ]:
M1 = Matriz
print(np.trace(M1+M2))
print(np.trace(M1)+np.trace(M2))

7
7


In [ ]:
alfa = 5
print(np.trace(alfa*M1))
print(alfa*np.trace(M1))

20
20


In [ ]:
print(np.trace(M1*M2))
print(np.trace(M2*M1))

25
25


In [ ]:
np.all(np.conjugate(M1)==M1.T)  #  Hermítica, matriz conjugada es igual a la transpuesta

False

In [ ]:
num_complejo = 3 + 5j
np.conjugate(num_complejo)

(3-5j)

In [ ]:
A = np.matrix([[1, 2-3j, 0],[2+3j, 5, 4-7j], [0, 4+7j, 5]])
A

matrix([[1.+0.j, 2.-3.j, 0.+0.j],
        [2.+3.j, 5.+0.j, 4.-7.j],
        [0.+0.j, 4.+7.j, 5.+0.j]])

In [ ]:
np.conjugate(A)

matrix([[1.-0.j, 2.+3.j, 0.-0.j],
        [2.-3.j, 5.-0.j, 4.+7.j],
        [0.-0.j, 4.-7.j, 5.-0.j]])

In [ ]:
if np.all(np.conjugate(A)==A.T):
  print("La matriz es hermítica")
else:
  print("La matriz no es hermítica")

La matriz es hermítica


In [ ]:
np.conjugate(A)==A.T

matrix([[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]])

In [ ]:
B = np.matrix([[4, 7, 6], [7, -3, -2], [9, -2, 10]])
B

matrix([[ 4,  7,  6],
        [ 7, -3, -2],
        [ 9, -2, 10]])

In [ ]:
B.T

matrix([[ 4,  7,  9],
        [ 7, -3, -2],
        [ 6, -2, 10]])

In [ ]:
if np.all(B.T==B):
  print("La matriz es simétrica")
else:
  print("La matriz no es simétrica")

La matriz no es simétrica


In [ ]:
np.all(B.T==B)

False

Determinante

In [ ]:
M1

matrix([[ 4,  7, -2],
        [ 1, -6,  8],
        [-3, 10,  6]])

In [ ]:
linalg.det(M1)

-658.0

In [ ]:
# Propiedad: det(a*A) = a^n *det(A)
print(linalg.det(5*M1))
print(5**3*linalg.det(M1))

-82250.0
-82250.0


In [ ]:
# Propiedad: Si una fila o columna es nula, entonces la determinante es cero.

In [ ]:
A = np.matrix([[1,2,3],[0,0,0],[4,5,6]])
A

matrix([[1, 2, 3],
        [0, 0, 0],
        [4, 5, 6]])

In [ ]:
linalg.det(A)

0.0

In [ ]:
# Propiedad: Si una fila o columna es proporcional a otra fila o columna, su determinante es cero

In [ ]:
A = np.matrix([[1,2,3],[-5*1,-5*2,-5*3],[4,5,6]])
A

matrix([[  1,   2,   3],
        [ -5, -10, -15],
        [  4,   5,   6]])

In [ ]:
linalg.det(A)

0.0

In [ ]:
# Propiedad: si se intercambia una fila o columna entonces |A|=-|A|

In [ ]:
A = np.matrix([[1,-2,4],[7,9,-4],[3,8,-1]])
linalg.det(A)

149.0

In [ ]:
A2 = np.matrix([[3,8,-1],[7,9,-4],[1,-2,4]])
linalg.det(A2)

-149.0

In [ ]:
# Propiedad: det(AB) = det(A)*det(B)

In [ ]:
linalg.det(A*B)

-100426.0

In [ ]:
linalg.det(A)*linalg.det(B)

-100426.0

In [ ]:
# Propiedad: det(A^k)=det(A)^k

In [ ]:
A*A

matrix([[ -1,  12,   8],
        [ 58,  35,  -4],
        [ 56,  58, -19]])

In [ ]:
A**2

matrix([[ -1,  12,   8],
        [ 58,  35,  -4],
        [ 56,  58, -19]])

In [ ]:
A**3

matrix([[107, 174, -60],
        [291, 167,  96],
        [405, 258,  11]])

In [ ]:
print(linalg.det(A**3))
print(linalg.det(A)**3)

3307949.0000000014
3307949.0


In [ ]:
# Propiedad det(A^-1) = 1/det(A)

In [ ]:
print(linalg.det(A.I))
print(1/linalg.det(A))

0.006711409395973156
0.006711409395973154


In [ ]:
# Propiedad: si rango(A) < n entonces det(A) = 0

In [ ]:
linalg.null_space(A)

array([], shape=(3, 0), dtype=float64)

In [ ]:
C = np.matrix([[7, 1, -4, -2],[6, -12, 3, 1],[13, -11, -1, -1],[0, 5, 8, -6]])
C

matrix([[  7,   1,  -4,  -2],
        [  6, -12,   3,   1],
        [ 13, -11,  -1,  -1],
        [  0,   5,   8,  -6]])

In [ ]:
linalg.det(C)

-8.149037000748649e-13

In [ ]:
linalg.null_space(C).shape

(4, 1)

In [ ]:
np.linalg.matrix_rank(C)

3

Inversa

In [ ]:
# A^-1 = 1/det(A) * Adj(A)

In [ ]:
A = np.matrix([[2,-7,1],[0,8,3],[1,0,-12]])
A

matrix([[  2,  -7,   1],
        [  0,   8,   3],
        [  1,   0, -12]])

In [ ]:
A.I

matrix([[ 0.43438914,  0.3800905 ,  0.13122172],
        [-0.01357466,  0.11312217,  0.02714932],
        [ 0.0361991 ,  0.03167421, -0.07239819]])

In [ ]:
A.I*linalg.det(A)

matrix([[-96., -84., -29.],
        [  3., -25.,  -6.],
        [ -8.,  -7.,  16.]])

Triangular

In [ ]:
T = np.triu(A)
T

array([[  2,  -7,   1],
       [  0,   8,   3],
       [  0,   0, -12]])

In [ ]:
T*T

array([[  4,  49,   1],
       [  0,  64,   9],
       [  0,   0, 144]])

In [ ]:
T+T

array([[  4, -14,   2],
       [  0,  16,   6],
       [  0,   0, -24]])

In [ ]:
linalg.det(T)

-192.0

In [ ]:
np.prod(np.diag(T))

-192

In [ ]:
np.linalg.matrix_rank(T)

3

Transpuesta

In [ ]:
A

matrix([[  2,  -7,   1],
        [  0,   8,   3],
        [  1,   0, -12]])

In [ ]:
A.T

matrix([[  2,   0,   1],
        [ -7,   8,   0],
        [  1,   3, -12]])

In [ ]:
# A.T.T == A

In [ ]:
A.T.T

matrix([[  2,  -7,   1],
        [  0,   8,   3],
        [  1,   0, -12]])

In [ ]:
B

matrix([[ 4,  7,  6],
        [ 7, -3, -2],
        [ 9, -2, 10]])

In [ ]:
# (A+B).T == A.T + B.T

In [ ]:
(A+B).T

matrix([[ 6,  7, 10],
        [ 0,  5, -2],
        [ 7,  1, -2]])

In [ ]:
A.T + B.T

matrix([[ 6,  7, 10],
        [ 0,  5, -2],
        [ 7,  1, -2]])

In [ ]:
# (c*A).T == c*A.T

In [ ]:
(3*A).T

matrix([[  6,   0,   3],
        [-21,  24,   0],
        [  3,   9, -36]])

In [ ]:
3*(A.T)

matrix([[  6,   0,   3],
        [-21,  24,   0],
        [  3,   9, -36]])

In [ ]:
# (A*B).T == B.T * A.T

In [ ]:
(A*B).T

matrix([[ -32,   83, -104],
        [  33,  -30,   31],
        [  36,   14, -114]])

In [ ]:
B.T * A.T

matrix([[ -32,   83, -104],
        [  33,  -30,   31],
        [  36,   14, -114]])

Valores y vectores propios

In [ ]:
A

matrix([[  2,  -7,   1],
        [  0,   8,   3],
        [  1,   0, -12]])

In [ ]:
valores_propios, vectores_propios = linalg.eig(A)

In [ ]:
valores_propios

array([-12.14440153+0.j,   2.32820093+0.j,   7.8162006 +0.j])

In [ ]:
vectores_propios

array([[ 0.14139151, -0.99689763,  0.77128956],
       [ 0.14582044,  0.03680097, -0.63529323],
       [-0.97915517, -0.06957591,  0.03892217]])